// <auto-generated />
using System;
using ApartmentTriage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ApartmentTriage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApartmentTriageDbContext))]
    [Migration("20260527133457_202605271745_AddImageToMessage")]
    partial class _202605271745_AddImageToMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmentTriage.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<bool>("EmergencySuspected")
                        .HasColumnType("boolean")
                        .HasColumnName("emergency_suspected");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_message_id");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("text")
                        .HasColumnName("image_mime_type");

                    b.Property<string[]>("MatchedPhrases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("matched_phrases");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_messages_received_at");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_messages_resident_id");

                    b.HasIndex("ChannelType", "ExternalMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_channel_type_external_message_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ApartmentTriage.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("apartment_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("PendingClarificationTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_clarification_ticket_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("tr")
                        .HasColumnName("preferred_language");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whats_app_number");

                    b.HasKey("Id")
                        .HasName("pk_residents");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_residents_telegram_id")
                        .HasFilter("telegram_id IS NOT NULL");

                    b.HasIndex("WhatsAppNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_residents_whats_app_number")
                        .HasFilter("whats_app_number IS NOT NULL");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("ApartmentTriage.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AmbiguityReasonsJson")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ambiguity_reasons_json");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CategoryConfidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_confidence");

                    b.Property<string>("Context")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("EmbeddingVector")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding_vector");

                    b.Property<string>("EmergencyConfidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emergency_confidence");

                    b.Property<bool>("EmergencyConfirmedByLlm")
                        .HasColumnType("boolean")
                        .HasColumnName("emergency_confirmed_by_llm");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean")
                        .HasColumnName("is_emergency");

                    b.Property<string>("LocationHint")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_hint");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<string>("RoutingAction")
                        .HasColumnType("text")
                        .HasColumnName("routing_action");

                    b.Property<string>("SecondaryIssuesJson")
                        .HasColumnType("text")
                        .HasColumnName("secondary_issues_json");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_tickets_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tickets_created_at");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_tickets_resident_id");

                    b.HasIndex("SourceMessageId")
                        .HasDatabaseName("ix_tickets_source_message_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tickets_status");

                    b.HasIndex("IsEmergency", "Status")
                        .HasDatabaseName("ix_tickets_is_emergency_status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ApartmentTriage.Domain.Entities.Message", b =>
                {
                    b.HasOne("ApartmentTriage.Domain.Entities.Resident", "Resident")
                        .WithMany("Messages")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ApartmentTriage.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("ApartmentTriage.Domain.Entities.Resident", "Resident")
                        .WithMany("Tickets")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_residents_resident_id");

                    b.HasOne("ApartmentTriage.Domain.Entities.Message", "SourceMessage")
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_messages_source_message_id");

                    b.Navigation("Resident");

                    b.Navigation("SourceMessage");
                });

            modelBuilder.Entity("ApartmentTriage.Domain.Entities.Resident", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
